config:
  aws:region: us-west-2
  mob-code-server:settings:
    email: me@email.com
    github:
      enabled: false
    gitlab:
      enabled: true
      repositories:
      token: mygitlabtoken
      username: mygitlabuser
    hosted_zone: myawshostedzone.com
    instance:
      disk_size: 64
      hostname: seattle
      instance_type: t3a.large
      os_dist: ubuntu
      username: coder
