config:
  aws:region: us-west-2
  mob-server:settings:
    email: me@email.com
    gitlab:
      enabled: true
      repositories:
      token: mygitlabtoken
      username: mygitlabuser
    hosted_zone: myawshostedzone.com
    instance:
      disk_size: 128
      hostname: cod
      instance_type: t3a.xlarge
      os_dist: ubuntu
      resource_type: ec2
      username: gunner
      vpc_id: vpc-xxxx
    variables:
      ___GOLANG_VERSION___: 1.19.5
      ___NVM_VERSION___: 0.39.3
      ___SERVERLESS_VERSION___: 2.64.1
